// DON'T DELETE THIS COMMENT !!!

{--------------------------------------------}
{ Unit:      PhoneI.inc                      }
{ Version:   1.01                            }
{                                            }
{ Coder:     Yahe <hello@yahe.sh>            }
{                                            }
{ I'm NOT Liable For Damages Of ANY Kind !!! }
{--------------------------------------------}

// DON'T DELETE THIS COMMENT !!!

{$Define EnableLogCapability}
{$Define EnableSimCodeForm}

{.$Define DLLMethods}
{$Define ObjectMethods}
